## INTERVIEW 1

#### SQL SERVER
SELECT TOP 1 C.NAME, O.PRICE 
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.ORDER_ID = O.ID
WHERE O.ORDER_DATE <= DATEADD(year, 10, (SELECT MIN(ORDER_DATE) FROM ORDERS))
ORDER BY O.PRICE DESC

#### MY SQL
SELECT C.NAME, O.PRICE 
FROM CUSTOMERS C, ORDERS O 
WHERE C.ORDER_ID = O.ID AND
      O.ORDER_DATE <= DATE_ADD((SELECT MIN(ORDER_DATE) FROM ORDERS), interval 10 year)
ORDER BY O.PRICE DESC LIMIT 1

#### POSTGRESQL
SELECT C.NAME, O.PRICE 
FROM CUSTOMERS C, ORDERS O 
WHERE C.ORDER_ID = O.ID AND
      O.ORDER_DATE <= (SELECT MIN(ORDER_DATE FROM ORDERS) + INTERVAL 10 'year')
ORDER BY O.PRICE DESC LIMIT 1

## INTERVIEW 2
                       
#### SQL SERVER
SELECT C.NAME, O.PRICE
FROM ORDERS O
INNER JOIN CUSTOMERS C ON C.ORDER_ID = O.ID
WHERE O.PRICE = 
(
    SELECT MAX(PRICE) 
    FROM ORDERS 
    WHERE ORDER_DATE BETWEEN 
        (SELECT MIN(ORDER_DATE) FROM ORDERS) 
        AND 
        (SELECT DATEADD(year, 10, MIN(ORDER_DATE)) FROM ORDERS)
) 
ORDER BY O.ORDER_DATE
                       
#### MY SQL
SELECT C.NAME, O.PRICE
FROM ORDERS O
INNER JOIN CUSTOMERS C ON C.ORDER_ID = O.ID
WHERE O.PRICE = 
(
    SELECT MAX(PRICE) 
    FROM ORDERS 
    WHERE ORDER_DATE BETWEEN 
        (SELECT MIN(ORDER_DATE) FROM ORDERS) 
        AND 
        (SELECT DATE_ADD(MIN(ORDER_DATE), INTERVAL 10 year) FROM ORDERS)
) 
ORDER BY O.ORDER_DATE
                       
#### POSTGRESQL
SELECT C.NAME, O.PRICE
FROM ORDERS O
INNER JOIN CUSTOMERS C ON C.ORDER_ID = O.ID
WHERE O.PRICE = 
(
    SELECT MAX(PRICE) 
    FROM ORDERS 
    WHERE ORDER_DATE BETWEEN 
        (SELECT MIN(ORDER_DATE) FROM ORDERS) 
        AND 
        (SELECT MIN(ORDER_DATE) + INTERVAL 10 'year' FROM ORDERS)
) 
ORDER BY O.ORDER_DATE
